### ISSUE TITLE
Support negative values

### ISSUE THREAD

**Issue by iver56** [kmandov/d3-horizon-chart#1]
Hi :)
I want to use this plugin. However, it doesn't support negative values yet, and that's a dealbreaker. I'd like to help, but at the time of writing I have no experience with coding d3 plugins. Instead, I created a little test that could be useful when implementing proper support for negative values.

These are the colors that I set:
![image](https://cloud.githubusercontent.com/assets/1470603/13467393/54e72d76-e09e-11e5-8306-7a169234c001.png)

This is what cosine looks like (at the time of writing):
![image](https://cloud.githubusercontent.com/assets/1470603/13467376/4591bd32-e09e-11e5-926d-c24e75c19016.png)

http://iver.io/stuff/d3-horizon-chart.html

I was expecting to see all the variants of blue in the negative parts of the cosine series.

**Comment by kmandov** [comment]
Hello Iver,

Support for negative values is on my todo list. 

You can have a look at horizon.js in the cubism.js project, if you want to see how this can be implemented.

Regards,
Kiril
