### ISSUE TITLE
Most basic example?

### ISSUE THREAD

**Issue by ktravelet** [kmandov/d3-horizon-chart#3]
I really like the idea of this but its hard to get into at first.  

If possible could you put up an example with the absolute minimum?

Is the data array 1 dimensional ( y values only) or can it be 2 dimensional with x & y values?

Assuming I only have 1 div (#horizon), would the code be:

```
d3_selection.select("#horizon")
            .data(d3_array.range(0, 3).map(random))
            .enter()
            .append('div')
            .attr('class', 'horizon');

d3_horizon_chart.horizonChart()
                  .height(200)
                  .colors(["#abd9e9", "#fee090"]);
```

Thanks!

**Comment by kmandov** [comment]
Hi,

I published a newer version of d3-horizon-chart. It is now compatible with the stable version of D3 v.4.

Here is a sample usage example: https://bl.ocks.org/kmandov/a1abe4aa380fb8b4bd0b4c081a76ce13
